baseURL = 'https://bothzoli.github.io/'
languageCode = 'en-us'
title = 'bothzoli'
theme = "hello-friend-ng"
paginate = 10

[author]
  name = "bothzoli"

[params]
  dateform        = "2006 Jan 2"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  homeSubtitle = ""
  enableThemeToggle = true
  disableReadOtherPosts = false
  enableSharingButtons = true
  enableGlobalLanguageMenu = true

  description = "My new homepage and blog"
  keywords = "homepage, blog"
  images = [""]

  [params.footer]
    author = true
    trademark = true
    rss = true

[[params.social]]
  name = "github"
  url = "https://www.github.com/bothzoli/"

[[params.social]]
  name = "twitter"
  url = "https://twitter.com/bothzoli"

[taxonomies]
  category = "blog"
  tag      = "tags"
  series   = "series"

[languages]
  [languages.en.params]
    title = "bothzoli's blog"
    languageCode = 'en'
    readOtherPosts = "Read other posts"

    [[languages.en.menu.main]]
      weight = 10
      name   = "Blog"
      url    = "/posts"

    [[languages.en.menu.main]]
      weight  = 20
      name    = 'About'
      pageRef = '/about'

    [languages.en.params.logo]
      logoText = "bothzoli's blog"
      logoHomeLink = "/"

  [languages.hu.params]
    title = "bothzoli blogja"
    languageCode = 'hu'
    readOtherPosts = "Többi bejegyzés olvasása"

    [[languages.hu.menu.main]]
      weight = 10
      name   = "Blog"
      url    = "/posts"

    [[languages.hu.menu.main]]
      weight  = 20
      name    = 'Rólam'
      pageRef = '/about'

    [languages.hu.params.logo]
      logoText = "bothzoli blogja"
      logoHomeLink = "/hu"